blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Support via Discord
    url: https://discord.gg/ckbvBtDJgC
    about: Chat with other users and the Overseerr dev team
  - name: ðŸ’¬ Support via GitHub Discussions
    url: https://github.com/fallenbagel/jellyseerr/discussions
    about: Ask questions and discuss with other community members
