apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: jellyseerr-chart
description: Jellyseerr helm chart for Kubernetes
type: application
version: 2.1.1
appVersion: "2.3.0"
maintainers:
  - name: Jellyseerr
    url: https://github.com/Fallenbagel/jellyseerr
sources:
  - https://github.com/Fallenbagel/jellyseerr/tree/main/charts/jellyseerr
home: https://github.com/Fallenbagel/jellyseerr
